### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by AbdulBariKhan** [sandhyalaxmiK/Highlight-Text-in-pdf-using-PyMuPDF#1]

**Comment by sandhyalaxmiK** [comment]
what is your doubt, so that i can help you out

**Comment by AbdulBariKhan** [comment]
I didn't needed help on this but I wanted to get help on an issue that you have succeeded.

**Comment by AbdulBariKhan** [comment]
https://github.com/CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch/issues

**Comment by AbdulBariKhan** [comment]
If possible contact me on a.bari.ku@gmail.com
